import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./widgets/sidebar";
import { Header } from "./widgets/header";
import { NotificationDropdown } from "./features/notifications";
import { Main } from "./widgets/main";
import { MatrixBackground } from "./widgets/background";

const rubikSans = Rubik({
  variable: "--font-geist-sans",
  weight: ['300', '600', '900']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body  
      className={`${rubikSans.variable} w-screen h-screen justify-center items-center overflow-x-hidden pb-10 bg-[#111] relative no-copy
        [&::-webkit-scrollbar]:w-0
      `}>

        <Sidebar/>
        <MatrixBackground />
        
        <Main> 
          <Header/>
          {children}
        </Main>

        {/* Modals menus */}
        <NotificationDropdown/>
      </body>
    </html>
  );
}
