import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/elements/sidebar/Sidebar";
import Header from "./components/elements/header/Header";
import Bg from "./components/other/bg";
import NotificationDropdawn from "./components/ui/NotificationDropdown";
import Main from "./components/main/Main";
import MatrixBackground from "./components/ui/MatrixBackground";

const rubikSans = Rubik({
  variable: "--font-geist-sans",
  weight: ['300', '600', '900']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body  
      className={`${rubikSans.variable} w-screen h-screen justify-center items-center overflow-x-hidden pb-10 bg-[#111] relative no-copy
        [&::-webkit-scrollbar]:w-0
      `}>

        <Sidebar/>
        <MatrixBackground />
        <Bg />
        
        <Main> 
          <Header/>
          {children}
        </Main>

        {/* Modals menus */}
        <NotificationDropdawn/>
      </body>
    </html>
  );
}
