// app/constants/genres.ts (исправил на правильное написание "genres")
export interface Genre {
    title: string;
    slugName: string;
}

export const genres: Genre[] = [
    { title: 'Боевик', slugName: 'action' },
    { title: 'Комедия', slugName: 'comedy' },
    { title: 'Драма', slugName: 'drama' },
    { title: 'Триллер', slugName: 'thriller' },
    { title: 'Ужасы', slugName: 'horror' },
    { title: 'Фантастика', slugName: 'sci-fi' },
    { title: 'Фэнтези', slugName: 'fantasy' },
    { title: 'Мелодрама', slugName: 'melodrama' },
    { title: 'Приключения', slugName: 'adventure' },
    { title: 'Детектив', slugName: 'detective' },
    { title: 'Криминал', slugName: 'crime' },
    { title: 'Вестерн', slugName: 'western' },
    { title: 'Исторический', slugName: 'historical' },
    { title: 'Биография', slugName: 'biography' },
    { title: 'Военный', slugName: 'military' },
    { title: 'Мюзикл', slugName: 'musical' },
    { title: 'Семейный', slugName: 'family' },
    { title: 'Мультфильм', slugName: 'animation' },
    { title: 'Аниме', slugName: 'anime' },
    { title: 'Документальный', slugName: 'documentary' },
    { title: 'Нуар', slugName: 'noir' },
    { title: 'Катастрофа', slugName: 'disaster' },
    { title: 'Спортивный', slugName: 'sports' },
    { title: 'Мистика', slugName: 'mystery' },
    { title: 'Экшн', slugName: 'action-movie' },
    { title: 'Артхаус', slugName: 'arthouse' },
    { title: 'Постапокалипсис', slugName: 'post-apocalyptic' },
    { title: 'Киберпанк', slugName: 'cyberpunk' },
    { title: 'Стимпанк', slugName: 'steampunk' },
    { title: 'Слэшер', slugName: 'slasher' },
    { title: 'Психологический триллер', slugName: 'psychological-thriller' },
    { title: 'Супергеройский', slugName: 'superhero' },
    { title: 'Романтическая комедия', slugName: 'romantic-comedy' },
    { title: 'Чёрная комедия', slugName: 'black-comedy' },
    { title: 'Научная фантастика', slugName: 'science-fiction' },
    { title: 'Космическая опера', slugName: 'space-opera' },
    { title: 'Эпическое фэнтези', slugName: 'epic-fantasy' },
    { title: 'Урбан-фэнтези', slugName: 'urban-fantasy' },
    { title: 'Паропанк', slugName: 'steampunk' },
    { title: 'Социальная драма', slugName: 'social-drama' },
    { title: 'Политический триллер', slugName: 'political-thriller' },
    { title: 'Эротика', slugName: 'erotic' },
    { title: 'Экспериментальный', slugName: 'experimental' }
];